In [ ]:
 import numpy as np

In [ ]:
A = np.array([[4., 1., 1.], [1., 3., 2.], [1.,2.,5.]])

In [ ]:
def jacobo_el_bobo(A,tolerancia=1e-9,itmax = 1000):
  max=A[0][0]
  i_=0
  j_=0
  R= np.zeros_like(A)
  H = np.zeros_like(A)
  for i in range(len(A)):
    for j in range(len(A[0])):
      if i != j:
        if A[i][j] > max:
          max = A[i][j]
          i_ = i
          j_ = j
  if A[i_][i_] == A[j_][j_]:
    x = np.pi/4
  else:
    x = 0.5*np.arctan(2*max/A[i_][i_]*A[j_][j_])  
  R[0][0] = np.cos(x)
  R[1][1] = np.cos(x)
  R[0][1] = -np.sin(x)
  R[1][0] = np.sin(x)
  R[2][2] = 1
  H = np.flip(R)
  D = R*A*H
  return D

o = jacobo_el_bobo(A)

(array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))

In [ ]:
def valorp(D,c,itmax=1000,tolerancia=1e-18):
  n = D.shape[0]
  v0 = np.zeros(n)
  v0[c] = 1.        
  lambda0 = np.inf  
  for k in range(itmax):
    v1 = np.dot(A,v0)
    lambda1 = v1[0]/v0[0]
    v1 = v1/np.linalg.norm(v1) 
    if np.abs(lambda0 - lambda1) <= tolerancia:
        break
    lambda0 = lambda1
    v0 = v1
                 
  return lambda0,v0

In [ ]:
def Tensor(v):
    
    n = v.shape[0]
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            T[i,j] = v[i]*v[j]
    
    return T

In [ ]:
def GetEigValues(A):
    
    A1 = A.copy()
    
    values = np.zeros(A1.shape[0])
    vectors = np.zeros_like(A1)
    
    for i in range(A.shape[0]):
        
        l,v = valorp(A1,i) 
        
        values[i] = l
        vectors[:,i] = v
        B = A1 - l*Tensor(v)
        A1 = B
        
    return values,vectors

In [ ]:
  y = GetEigValues(o)
  y

<ipython-input-11-94a5bd9201d0>:8: RuntimeWarning: divide by zero encountered in double_scalars
  lambda1 = v1[0]/v0[0]
<ipython-input-11-94a5bd9201d0>:10: RuntimeWarning: invalid value encountered in double_scalars
  if np.abs(lambda0 - lambda1) <= tolerancia:


(array([6.89510652, 6.89510652, 6.89510652]),
 array([[0.43170413, 0.43170413, 0.43170413],
        [0.49725362, 0.49725362, 0.49725362],
        [0.75257583, 0.75257583, 0.75257583]]))

In [ ]:
np.linalg.eig(A)

(array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))