In [ ]:
import numpy as np

A = np.array([[4, -2, 1], [20, -7, 12], [-8, 13, 17]])

n = A.shape[0]
L = np.eye(n)
U = np.zeros((n, n))

for i in range(n):
    U[i, i:] = A[i, i:] - L[i, :i] @ U[:i, i:]
    L[i+1:, i] = (A[i+1:, i] - L[i+1:, :i] @ U[:i, i]) / U[i, i]

print("L =")
print(L)
print("U =")
print(U)


L =
[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
U =
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]
