In [2]:
import numpy as np

def func(x):
    
    return 60 * x[2] + 3 * np.exp(-x[0] * x[1]) + 10 * np.pi - 3

def jacobian(func, x, h):

    n = len(x)
    J = np.zeros((n, n))
    fx = func(x)
    
    for i in range(n):
      
        xph = x.copy()
        xph[i] += h
        fxph = func(xph)
        J[:, i] = (-fxph + 8 * fx - 8 * func(x - h) + func(x - 2 * h)) / (12 * h)
    
    return J



In [3]:
x = np.array([0.5, 0.5, 0.5])
J = jacobian(func, x, h=0.01)

print("El Jacobiano estimado en el punto x=(0.5, 0.5, 0.5) es:")
print(J)

El Jacobiano estimado en el punto x=(0.5, 0.5, 0.5) es:
[[28.93280004 28.93280004 23.83569291]
 [28.93280004 28.93280004 23.83569291]
 [28.93280004 28.93280004 23.83569291]]


In [7]:
def jacobian2(func, x, h=0.01):

    n = len(x)
    J = np.zeros((n, n))
    fx = func(x)
    
    for i in range(n):
        
        xph = x.copy()
        xph[i] += h
        fxph = func(xph)
        J[:, i] = (fxph - fx) / h
    
    return J

J2 = jacobian2(func, x, h=0.01)

print("El Jacobiano estimado con orden O(h^2) en el punto x=(0.5, 0.5, 0.5) es:")
print(J2)

El Jacobiano estimado con orden O(h^2) en el punto x=(0.5, 0.5, 0.5) es:
[[-1.16528553 -1.16528553 60.        ]
 [-1.16528553 -1.16528553 60.        ]
 [-1.16528553 -1.16528553 60.        ]]


In [8]:
for i, h in enumerate([0.1, 0.05, 0.01, 0.005, 0.001]):
    J4 = jacobian(func, x, h=h)
    print(f"El Jacobiano estimado con orden O(h^4) y h={h} en el punto x=(0.5, 0.5, 0.5) es:")
    print(J4)
    print(f"Diferencia con respecto al Jacobiano estimado con orden O(h^2): {np.max(np.abs(J4 - J2)):.8f}")
    print()

El Jacobiano estimado con orden O(h^4) y h=0.1 en el punto x=(0.5, 0.5, 0.5) es:
[[28.96592229 28.96592229 23.87096589]
 [28.96592229 28.96592229 23.87096589]
 [28.96592229 28.96592229 23.87096589]]
Diferencia con respecto al Jacobiano estimado con orden O(h^2): 36.12903411

El Jacobiano estimado con orden O(h^4) y h=0.05 en el punto x=(0.5, 0.5, 0.5) es:
[[28.94743035 28.94743035 23.85128705]
 [28.94743035 28.94743035 23.85128705]
 [28.94743035 28.94743035 23.85128705]]
Diferencia con respecto al Jacobiano estimado con orden O(h^2): 36.14871295

El Jacobiano estimado con orden O(h^4) y h=0.01 en el punto x=(0.5, 0.5, 0.5) es:
[[28.93280004 28.93280004 23.83569291]
 [28.93280004 28.93280004 23.83569291]
 [28.93280004 28.93280004 23.83569291]]
Diferencia con respecto al Jacobiano estimado con orden O(h^2): 36.16430709

El Jacobiano estimado con orden O(h^4) y h=0.005 en el punto x=(0.5, 0.5, 0.5) es:
[[28.93097435 28.93097435 23.83374584]
 [28.93097435 28.93097435 23.83374584]
 [28.9309